import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../../store';

import { v4 as uuidv4 } from 'uuid';
import { Labels } from '../../../../enums';
import { camelCase } from '../../../../utils';
import {
  createItem,
  deleteItem,
  getItems,
  updateItem,
} from '../../../utils/api';
import { getFeedings } from './feedingAPI';

const initialState: InitialStateType<Feeding> = {
  items: [],
  isLoading: false,
  isLoaded: false,
  selectedFeatureId: '',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getFeedingsAsync = createAsyncThunk(
  'feeding/getFeedings',
  async () => {
    // The value we return becomes the `fulfilled` action payload
    const response = await getItems<Feeding>({
      featureName: camelCase(Labels.FEEDING),
    });
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const createFeedingAsync = createAsyncThunk(
  'feeding/createFeeding',
  async (newItem: Feeding) => {
    // The value we return becomes the `fulfilled` action payload
    const response = await createItem<Feeding>({
      featureName: camelCase(Labels.FEEDING),
      newItem,
    });
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const updateFeedingAsync = createAsyncThunk(
  'feeding/updateFeeding',
  async (updatedItem: Feeding) => {
    // The value we return becomes the `fulfilled` action payload
    const response = await updateItem<Feeding>({
      featureName: camelCase(Labels.FEEDING),
      updatedItem,
    });
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const deleteFeedingAsync = createAsyncThunk(
  'feeding/deleteFeeding',
  async (id: string) => {
    // The value we return becomes the `fulfilled` action payload
    const response = await deleteItem({
      featureName: camelCase(Labels.FEEDING),
      id,
    });
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const feedingSlice = createSlice({
  name: 'feeding',
  initialState,
  reducers: {
    setSelectedFeatureId: (state, action: PayloadAction<string>) => {
      state.selectedFeatureId = action.payload;
    },
    deleteFeature: (state, action: PayloadAction<string>) => {
      state.items = state.items.filter((item) => item.id !== action.payload);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getFeedingsAsync.pending, (state) => {
        state.isLoading = true;
      })
      .addCase(getFeedingsAsync.fulfilled, (state, action) => {
        state.items = action.payload;
        state.isLoading = false;
        state.isLoaded = true;
      })
      .addCase(getFeedingsAsync.rejected, (state) => {
        state.isLoading = false;
        state.isLoaded = false;
      })
      .addCase(createFeedingAsync.pending, (state) => {
        state.isLoading = true;
      })
      .addCase(createFeedingAsync.fulfilled, (state, action) => {
        state.items = state.items.concat(action.payload);
        state.isLoading = false;
        state.isLoaded = true;
        state.selectedFeatureId = action?.payload[0].id || '';
      })
      .addCase(createFeedingAsync.rejected, (state) => {
        state.isLoading = false;
        state.isLoaded = false;
      })
      .addCase(updateFeedingAsync.pending, (state) => {
        state.isLoading = true;
      })
      .addCase(updateFeedingAsync.fulfilled, (state, action) => {
        const updatedIds = action.payload.map((item) => item.id);

        state.items = [
          ...state.items
            .filter((item) => !updatedIds.includes(item.id))
            .concat(action.payload),
        ];
        state.isLoading = false;
        state.isLoaded = true;
      })
      .addCase(updateFeedingAsync.rejected, (state) => {
        state.isLoading = false;
        state.isLoaded = false;
      })
      .addCase(deleteFeedingAsync.pending, (state) => {
        state.isLoading = true;
      })
      .addCase(deleteFeedingAsync.fulfilled, (state, action) => {
        // TODO Remove this test code
        console.log('ELITEST delete feeding async', {
          payload: action.payload,
        });
        //^ TODO Remove this test code
        state.items = [
          ...state.items.filter((item) => item.id !== action.payload.id),
        ];
        state.isLoading = false;
        state.isLoaded = true;

        if (state.selectedFeatureId === action.payload.id) {
          state.selectedFeatureId = '';
        }
      })
      .addCase(deleteFeedingAsync.rejected, (state) => {
        state.isLoading = false;
        state.isLoaded = false;
      });
  },
});

export const { deleteFeature, setSelectedFeatureId } = feedingSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.feeding.value)`
export const selectFeatureItems = (state: RootState) => state.feeding.items;
export const selectFeatureIsLoading = (state: RootState) =>
  state.feeding.isLoading;
export const selectFeatureIsLoaded = (state: RootState) =>
  state.feeding.isLoaded;
export const selectSelectedFeatureId = (state: RootState) =>
  state.feeding.selectedFeatureId;
export const selectSelectedFeatureItem = (state: RootState) =>
  state.feeding.items.find(
    (item) => item.id === selectSelectedFeatureId(state)
  );

export default feedingSlice.reducer;
